config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'customers#index'
  resources :customers, only: [:index]
  resources :uploads, only: [:create]
end

app/models/customer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: customers
#
#  id         :bigint           not null, primary key
#  first_name :string
#  last_name  :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Customer < ActiveRecord::Base
  has_one :vehicle

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name,  presence: true, length: { maximum: 50 }
  validates :email,      presence: true,
                         length: { maximum: 255 },
                         format: { with: URI::MailTo::EMAIL_REGEXP },
                         uniqueness: { case_sensitive: false }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/vehicle.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: vehicles
#
#  id           :bigint           not null, primary key
#  customer_id  :bigint
#  vehicle_type :string
#  name         :string
#  length       :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Vehicle < ActiveRecord::Base
  include LengthParser

  belongs_to :customer

  validates :vehicle_type, presence: true
  validates :name, presence: true
  validates :length, presence: true # Length is always in feet, no partial feet.

  enum vehicle_type: %i[sailboat motorboat rv campervan bicycle]

  before_validation :parse_length

  def formatted_vehicle_type
    vehicle_type == 'rv' ? 'RV' : vehicle_type.capitalize
  end

  private

  def parse_length
    parsed_length = LengthParser.parse(length)
    if parsed_length
      self.length = parsed_length
    else
      errors.add(:length, 'invalid length format')
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def render_flash(type, message)
    render turbo_stream: turbo_stream.prepend('flash-messages', partial: 'shared/flash',
                                                                locals: { type:, message: })
  end
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  include SortHelper

  def index
    @sort_column = params[:sort] || 'first_name'
    @sort_direction = params[:direction] || 'asc'
    @customers = formatted_customer_data
    respond_to(&:html)
  end

  private

  def formatted_customer_data
    Customer.includes(:vehicle).order("#{@sort_column} #{@sort_direction}").map do |customer|
      {
        full_name: customer.full_name,
        email: customer.email,
        vehicle_type: customer.vehicle.formatted_vehicle_type,
        vehicle_name: customer.vehicle.name,
        vehicle_length: "#{customer.vehicle.length} ft."
      }
    end
  end
end

app/controllers/uploads_controller.rb
# frozen_string_literal: true

class UploadsController < ApplicationController
  MAX_FILE_SIZE = 5.megabytes
  ACCEPTED_TYPES = %w[text/plain].freeze

  def create
    result = FileService.new(params[:file]).process
    result[:success] ? handle_success(result) : handle_failure(result)
  end

  private

  def handle_success(result)
    @customers = Customer.includes(:vehicle).order(:last_name)
    respond_to do |format|
      format.html do
        flash[:success] = result[:message]
        redirect_to customers_path
      end
    end
  end

  def handle_failure(result)
    respond_to do |format|
      format.html do
        flash[:error] = format_error_message(result)
        redirect_to customers_path
      end
    end
  end

  def format_error_message(result)
    message = result[:message]
    if result[:details].present?
      result[:details].each do |detail|
        message += "<li class='alert-details-text'>#{detail}</li>"
      end
      message += '</ul>'
    end
    message
  end
end

app/helpers/sort_helper.rb
# frozen_string_literal: true

module SortHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to(customers_path(sort: column, direction:), data: { turbo_stream: true }) do
      safe_join([title, sort_indicator(column)])
    end
  end

  private

  def sort_indicator(column)
    if column == sort_column
      direction = sort_direction == 'asc' ? '↑' : '↓'
      tag.small(direction, class: 'small pl-1 align-text-bottom text-gray-500')
    else
      tag.small('↕', class: 'small pl-1 align-text-bottom text-gray-500')
    end
  end

  def sort_column
    params[:sort] || 'first_name'
  end

  def sort_direction
    params[:direction] || 'asc'
  end
end

app/views/customers/_list.html.erb
<table>
  <thead class="bg-gray-100">
    <tr>
      <th>
        <%= sortable 'first_name', 'Full Name' %>
      </th>
      <th>Email</th>
      <th>
        <%= sortable 'vehicles.vehicle_type', 'Vehicle Type' %>
      </th>
      <th>Vehicle Name</th>
      <th>Vehicle Length</th>
    </tr>
  </thead>
  <tbody>
    <% customers.each do |customer| %>
      <tr class="border-t">
        <td><%= customer[:full_name] %></td>
        <td><%= customer[:email] %></td>
        <td><%= customer[:vehicle_type] %></td>
        <td><%= customer[:vehicle_name] %></td>
        <td><%= customer[:vehicle_length] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/index.html.erb
<div class='bg-white rounded-lg opacity-95 mx-auto w-fit p-4'>
  <div id="flash-messages">
    <% flash.each do |type, message| %>
      <%= render 'shared/flash', flash_type: type, message: message %>
    <% end %>
  </div>
  <h2 class="text-1xl font-normal tracking-tight text-gray-600/90 sm:text-2xl py-3 text-center">Upload Vehicles</h2>
  <%= form_with url: uploads_path, method: :post, class: 'w-3/5 mx-auto flex flex-col' do |form| %>
    <div class="col-span-full">
      <div id="drop-zone" class="flex justify-center rounded-lg border border-dashed border-gray-900/25 px-3 py-4">
        <div class="text-center">
          <div class="flex text-sm leading-6 text-gray-600">
            <label for="file-upload" class="relative cursor-pointer rounded-md bg-white font-semibold text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500">
              <span>Upload a file</span>
              <%= form.file_field :file, id: 'file-upload', direct_upload: true, data: { upload_target: 'file' }, class: 'hidden' %>
            </label>
            <p class="pl-1">or drag and drop</p>
          </div>
          <p class="text-xs text-gray-500">TXT up to 5MB</p>
        </div>
      </div>
      <p id="file-name" class="text-sm mt-2 text-gray-600 font-semibold"></p>
    </div>

    <div class="flex justify-center mt-2">
      <%= form.submit 'Upload',
        id: 'submit-button',
        data: { upload_target: 'submit', action: 'click->upload#submitForm' },
        class: 'rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 transition duration-150 ease-in-out opacity-50 cursor-not-allowed',
        disabled: true
      %>
    </div>
  <% end %>

  <% if @customers.count.positive? %>
    <div id="customer-list" class="mx-auto border rounded-lg mt-4 min-w-96">
      <%= render 'list', customers: @customers %>
    </div>
  <% else %>
    <div class="min-w-96 mt-2">
      <p class="text-sm text-center text-gray-500">Upload your guest list to enhance the camping experience for visitors at your campground.</p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Outdoor.sy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body style="background-image: url('<%= asset_path('camping.jpg') %>'); background-size: cover; background-position: center;">>
    <main class='container mx-auto px-4'>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="alert-<%= flash_type %>" role="alert">
  <span class="font-medium"><%= message.html_safe %></span>
</div>